### ISSUE TITLE
Not so much an issue per se

### ISSUE THREAD

**Issue by Dhop84** [Hiltronix/plugin.video.sickrage#7]
Hi I don't no what I've done  wrong but I can get this working fine on my laptop where sickrage is installed but I cant add this to my other computer, do I need to install sickrage onto that computer to?

**Comment by Hiltronix** [comment]
You only need to have the SickRage plugin installed on the the other computer.  You only need the SickRage server software installed on a single computer.
Have you configured the plugin settings correctly?  Make sure you have the set the correct IP address for the computer where you have the SickRage server running.  And of course the username, password, etc.
If you are certain you have set all the plugin config settings correctly, then we will have to see what error messages are generated in the Kodi log file.
