### ISSUE TITLE
TMDB API key needs to be provided for module.metahandler

### ISSUE THREAD

**Issue by troych** [Hiltronix/plugin.video.sickrage#8]
Hi there,

I've just installed this plugin and noticed some new errors in my kodi.log, looks like the module.metahandler TMDB api key got revoked and he depends on addons devs using their own key from now on. See: https://github.com/Eldorados/script.module.metahandler/issues/2

Any chance this addon could be updated to reflect these changes? A temporary solution would be to hunt my own key and add it to module.metahandler but that would not fix it for everybody else of course.

**Comment by Hiltronix** [comment]
Thanks for the notice.  I'll look into the issue and get back to you with an update.

**Comment by Hiltronix** [comment]
The addon now has it's own API key for TMDB.  The version is 1.3.16.  Please let me know if it solves the issue.

**Comment by troych** [comment]
Yup, no more errors. Thanks for the quick fix, I'll close this.
